<?php

if(!function_exists('html_variable')) {
  function html_variable() {
  
		$data = [
			//html variables
			'title' => '',
			'dashboard' => '',
			'items_menu_status' => '',
			'items_menu_display' => '',
			'registration' => '',
			'ul_items' => '',
			'indirect_list' => '',
			// 'item_stocks' => '',
			'pullout_items' => '',
			'listof_pullouts' => '',
			'ul_tools' => '',
			'consumeables' => '',
			'history' => '',
			'listof_warranty' => '',
			'ul_reports' => '',
			'daily_reports' => '',
			'weekly_reports' => '',
			'monthly_reports' => '',
			'make_quotation' => '',
			'sales_quotation_list' => '',
			'make_drform' => '',
			'make_warrantyform' => '',
			'ul_formslisting' => '',
			'list_quote' => '',
			'list_drform' => '',
			'list_warrantyform' => '',
			'inquiry_status' => '',
			'inquiry_href' => '',
			'inquiry_existing' => '',
			'inquiry_new' => '',
			'schedules' => '',
			'forms_menu_status' => '',
			'ul_forms' => '',
			'Generate_dispatch' => '',
			'dispatch_menu_status' => '',
			'dispatch_forms' => '',
			'dispatch_list' => '',
			'dispatch' => '',
			'sales_quotation_status' => '',
			'sales_quotation_href' => '',
			'sales_menu_status' => '',
			'sales_dispatch' => '',
			'Generate_sales_dispatch' => '',
			'sales_dispatch_list' => '',
			'salesdispatch' => '',
			'servicecall' => '',
			'li_servicereport' => '',
			'ul_servicereport' => '',
			'encode_sr' => '',
			'sr_listing' => '',
			'project_report' => '',
			'project_report_href' => '',
			'project_report_add' => '',
			'project_report_list' => '',
			'li_payroll' => '',
			'pullout_scan' => '',
			'requisition_form' => '',
			'requisition_tree' => '',
			'requisition_add' => '',
			'requisition_display' => '',
			'requisition_pending' => '',
			'requisition_accepted' => '',
			'requisition_filed' => '',
			'requisition_discarded' => '',
			'li_vendor_list' => '',
			'li_generated_po' => '',

			'category' => '' //for Get Items Masterlist
		];

    return $data;
  }
}